ops:
  stream_and_predict:
    config:
      topic: 'DataTopic'
      batch_size: 2
      path_current_model: '/opt/dagster/app/models/mnist/initial_model.H5'
      stream_timeout_ms: 30000
resources:
  db:
    config:
      conn_str: "postgresql://vectoraiuser:password@predictions_postgresql:6666/predictions_postgresql"
